### ISSUE TITLE
Answer of `exercisesV0.2/collections/hashmap2.rs` is invalid

### ISSUE THREAD

**Issue by lihsai0** [master-davidlee/rustlings_answer#1]
> You are not allowed to insert any more of these fruits!

It should be:

``` rust
for fruit in fruit_kinds {
    basket.entry(fruit).or_insert(1); // or other numbers
}
```

**Comment by master-davidlee** [comment]
Thanks for your advice! I will update the answer soon

**Comment by master-davidlee** [comment]
> > You are not allowed to insert any more of these fruits!
> 
> It should be:
> 
> ```rust
> for fruit in fruit_kinds {
>     basket.entry(fruit).or_insert(1); // or other numbers
> }
> ```

Ok, I fix the issue and update to lastest exercises
